import assert from 'node:assert/strict';
import {newGame,action,sequence,meldOptions,score,publicGame,value,type Card} from '../lib/game.ts';
const cards=(ranks:number[],s='♥'):Card[]=>ranks.map((r,i)=>({id:`${s}-${r}-${i}`,r,s}));
for(const n of [2,4]){
 let g=newGame('test',Array.from({length:n},(_,i)=>'Player '+i));
 for(let i=1;i<n;i++)g=action(g,i,'join');
 assert.equal(g.status,'playing');assert.equal(g.stock.length,n===2?63:41);
 const all=[...g.stock,...g.discard,...g.mortos.flat(),...g.players.flatMap(p=>p.hand)];assert.equal(all.length,108);assert.equal(new Set(all.map(c=>c.id)).size,108);assert.equal(all.filter(c=>c.r===0).length,4);
 assert.equal(publicGame(g,0).players[1].hand.length,0);
 assert.throws(()=>action(g,1,'draw'));g=action(g,0,'draw');assert.throws(()=>action(g,0,'draw'));
 g=action(g,0,'discard',{ids:[g.players[0].hand[0].id]});assert.equal(g.turn,1);
 assert.throws(()=>action(g,1,'finish'));g=action(g,0,'finish');assert.equal(g.history.length,1);assert.equal(g.batterSeat,null);assert.throws(()=>action(g,0,'finish'));
 const totals=[...g.totals];g=action(g,0,'next');assert.equal(g.round,2);assert.deepEqual(g.totals,totals);assert.equal(g.batterSeat,null);
}
let stopped=newGame('stop-round',['Ana','Beto']);stopped=action(stopped,1,'join');
stopped=action(stopped,0,'draw');
assert.throws(()=>action(stopped,1,'stop'),/Só o anfitrião/);
const beforeStop=structuredClone(stopped);
stopped=action(stopped,0,'stop');
assert.equal(stopped.status,'finished');assert.equal(stopped.roundStopped,true);
assert.deepEqual(stopped.totals,beforeStop.totals);assert.deepEqual(stopped.history,beforeStop.history);
assert.equal(stopped.players.every(p=>p.hand.length===0),true);
assert.equal(stopped.stock.length+stopped.discard.length+stopped.mortos.length+stopped.melds.length,0);
assert.throws(()=>action(stopped,0,'stop'),/em andamento/);
assert.throws(()=>action(stopped,0,'finish'),/encerrar a rodada/);
stopped=action(stopped,0,'next');assert.equal(stopped.round,2);assert.equal(stopped.roundStopped,false);
assert.equal(stopped.players.every(p=>p.hand.length===11),true);assert.deepEqual(stopped.totals,[0,0]);
stopped=action(stopped,0,'finish');const countedTotals=[...stopped.totals],countedHistory=structuredClone(stopped.history);
stopped=action(stopped,0,'next');stopped=action(stopped,0,'stop');
assert.equal(stopped.round,3);assert.deepEqual(stopped.totals,countedTotals);assert.deepEqual(stopped.history,countedHistory);
assert.equal(sequence(cards([1,2,3,4,5,6,7]))?.clean,true);
assert.equal(sequence(cards([3,4,2,6,7,8,9]))?.clean,false);
assert.equal(sequence(cards([3,4,2,6,7,8,9]),{'♥-2-2':6}),null);
const picturedRun=cards([1,2,3,4,5,6,7,8,9,10,11,12],'♦');
assert.deepEqual(sequence(picturedRun,{'♦-2-1':2})?.wilds,{},'A 2 of the run suit in its own position is natural even if previously declared wild');
assert.equal(sequence(picturedRun,{'♦-2-1':2})?.clean,true);
assert.equal(sequence([{id:'other-two',r:2,s:'♥'},...cards([3,4,5,6,7,8],'♦')],{ 'other-two':2 })?.clean,false,'A 2 from another suit is wild');
assert.equal(sequence(cards([11,12,13,1]))?.clean,true);
assert.deepEqual(sequence(cards([1,13,12],'♣'))?.cards.map(c=>c.r),[12,13,1]);
assert.equal(sequence(cards([3,5,7])),null);
assert.equal(sequence([...cards([3,4]),...cards([5],'♠')]),null);
const diamondRun=[{id:'three-d',r:3,s:'♦'},{id:'four-d',r:4,s:'♦'},{id:'wild-h',r:2,s:'♥'}];
const naturalTwo={id:'natural-d',r:2,s:'♦'};
assert.deepEqual(sequence([...diamondRun,naturalTwo],{'wild-h':5})?.cards.map(c=>c.id),['natural-d','three-d','four-d','wild-h']);
assert.deepEqual(sequence([...diamondRun,naturalTwo],{'wild-h':5})?.wilds,{'wild-h':5});
assert.equal(sequence([...diamondRun,naturalTwo],{'wild-h':5})?.clean,false);
assert.equal(sequence([...diamondRun,{...naturalTwo,s:'♠'}],{'wild-h':5}),null);
assert.equal(sequence(cards([2,3,4],'♦'))?.clean,true,'A 2 in its own suit and position is natural');
let picturedGame=newGame('pictured',['Ana','Beto']);picturedGame=action(picturedGame,1,'join');
picturedGame.melds=[{id:'pictured-run',team:0,cards:picturedRun,wilds:{'♦-2-1':2}}];
assert.equal(score(picturedGame)[0].canastas,200,'An existing saved meld must score clean without waiting for another move');
picturedGame=action(picturedGame,0,'finish');
assert.equal(picturedGame.history[0].scores[0].canastas,200,'The dashboard must persist the clean bonus');
let evolved=newGame('evolved',['Ana','Beto']);evolved=action(evolved,1,'join');evolved.drawn=true;
evolved.players[0].hand=[{id:'natural-five',r:5,s:'♦'},{id:'spare',r:13,s:'♣'}];
evolved.melds=[{id:'evolved-run',team:0,cards:[...cards([3,4],'♦'),{id:'natural-two',r:2,s:'♦'},...cards([6,7,8,9],'♦')],wilds:{'natural-two':5}}];
assert.equal(score(evolved)[0].canastas,100);
assert.equal(meldOptions([evolved.players[0].hand[0]],evolved.melds[0]).some(o=>o.rank===2&&o.clean),true);
evolved=action(evolved,0,'meld',{ids:['natural-five'],meldId:'evolved-run',wildRank:2});
assert.deepEqual(evolved.melds[0].wilds,{});
assert.equal(score(evolved)[0].canastas,200);
let naturalGame=newGame('natural-two',['Ana','Beto']);naturalGame=action(naturalGame,1,'join');naturalGame.drawn=true;
naturalGame.players[0].hand=[naturalTwo,{id:'spare',r:8,s:'♣'}];
naturalGame.melds=[{id:'diamonds',team:0,cards:diamondRun,wilds:{'wild-h':5}}];
assert.deepEqual(meldOptions([naturalTwo],naturalGame.melds[0]).map(o=>o.rank),[1,5]);
const naturalPlayed=action(naturalGame,0,'meld',{ids:['natural-d'],meldId:'diamonds'});
assert.deepEqual(naturalPlayed.melds[0].cards.map(c=>c.id),['natural-d','three-d','four-d','wild-h']);
assert.deepEqual(naturalPlayed.melds[0].wilds,{'wild-h':5});
assert.equal(score(naturalPlayed)[0].cards,50);
assert.equal(action(naturalGame,0,'meld',{ids:['natural-d'],meldId:'diamonds',wildRank:1}).melds[0].wilds?.['wild-h'],1);
const dirtyWithNaturalTwo=structuredClone(naturalPlayed);dirtyWithNaturalTwo.melds[0].cards.push(...cards([6,7,8],'♦'));
assert.equal(score(dirtyWithNaturalTwo)[0].canastas,100);
let g=newGame('morto',['A','B']);g=action(g,1,'join');g.players[0].hand=cards([3,4,5]);g.drawn=true;g=action(g,0,'meld',{ids:g.players[0].hand.map(c=>c.id)});assert.equal(g.players[0].hand.length,11);assert.equal(g.taken[0],true);assert.equal(g.drawn,true);
g.players[0].hand=cards([9]);g.melds=[{id:'canasta',team:0,cards:cards([3,4,5,6,7,8,9])}];g=action(g,0,'discard',{ids:[g.players[0].hand[0].id]});assert.equal(g.winner,0);assert.equal(g.batterSeat,0);assert.equal(g.turn,1);assert.equal(score(g)[0].canastas,200);assert.equal(score(g)[0].out,100);
const stoppedAfterBatida=action(g,0,'stop');assert.equal(stoppedAfterBatida.winner,null);assert.equal(stoppedAfterBatida.batterSeat,null);assert.equal(stoppedAfterBatida.roundStopped,true);assert.deepEqual(stoppedAfterBatida.totals,[0,0]);assert.equal(stoppedAfterBatida.history.length,0);
g=action(g,0,'finish');assert.equal(g.batterSeat,0);g=action(g,0,'next');assert.equal(g.batterSeat,null);
let dirty=newGame('dirty',['A','B']);dirty=action(dirty,1,'join');dirty.taken[0]=true;dirty.drawn=true;dirty.players[0].hand=cards([10]);dirty.melds=[{id:'dirty-canasta',team:0,cards:cards([3,4,2,6,7,8,9]),wilds:{'♥-2-2':5}}];
assert.equal(score(dirty)[0].canastas,100);dirty=action(dirty,0,'discard',{ids:[dirty.players[0].hand[0].id]});assert.equal(dirty.winner,0);assert.equal(score(dirty)[0].out,100);
const noCanasta=structuredClone(dirty);noCanasta.winner=null;noCanasta.turn=0;noCanasta.drawn=true;noCanasta.players[0].hand=cards([11]);noCanasta.melds=[];assert.throws(()=>action(noCanasta,0,'discard',{ids:[noCanasta.players[0].hand[0].id]}),/canastra limpa ou suja/);
assert.equal(value({id:'two',r:2,s:'♠'}),20);assert.equal(value({id:'joker',r:0,s:'★'}),50);
assert.equal(sequence([...cards([3,5]),{id:'two',r:2,s:'♠'}],{two:4})?.suit,'♥');
let w=newGame('wild',['A','B']);w=action(w,1,'join');w.players[0].hand=[...cards([3,5]),{id:'joker',r:0,s:'★'}];w.drawn=true;
assert.throws(()=>action(w,0,'meld',{ids:w.players[0].hand.map(c=>c.id)}),/Escolha qual carta/);
assert.throws(()=>action(w,0,'meld',{ids:w.players[0].hand.map(c=>c.id),wildRank:6}),/Forme uma sequência/);
w=action(w,0,'meld',{ids:w.players[0].hand.map(c=>c.id),wildRank:4});
assert.equal(w.melds[0].wilds?.joker,4);assert.equal(w.melds[0].cards[1].id,'joker');assert.equal(score(w)[0].cards,60);
w.players[0].hand=[{id:'two',r:2,s:'♠'}];assert.throws(()=>action(w,0,'meld',{ids:['two'],meldId:w.melds[0].id,wildRank:6}),/no máximo um/);
let replace=newGame('replace-wild',['A','B']);replace=action(replace,1,'join');replace.drawn=true;
replace.players[0].hand=[{id:'natural-four',r:4,s:'♠'},{id:'spare',r:10,s:'♥'}];
replace.melds=[{id:'gap',team:0,cards:[{id:'three',r:3,s:'♠'},{id:'table-joker',r:0,s:'★'},...cards([5,6,7],'♠')],wilds:{'table-joker':4}}];
assert.deepEqual(meldOptions([replace.players[0].hand[0]],replace.melds[0]).map(o=>o.rank),[2,8]);
assert.deepEqual(meldOptions([replace.players[0].hand[0]],replace.melds[0])[0].cards.map(c=>c.id),['table-joker','three','natural-four','♠-5-0','♠-6-1','♠-7-2']);
assert.throws(()=>action(replace,0,'meld',{ids:['natural-four'],meldId:'gap'}),/Forme uma sequência/);
assert.throws(()=>action(replace,0,'meld',{ids:['natural-four'],meldId:'gap',wildRank:4}),/Forme uma sequência/);
assert.throws(()=>action(replace,0,'meld',{ids:['natural-four'],meldId:'gap',wildRank:9}),/Forme uma sequência/);
for(const [target,position] of [[2,0],[8,5]] as const){
 const moved=action(replace,0,'meld',{ids:['natural-four'],meldId:'gap',wildRank:target});
 assert.equal(moved.melds[0].wilds?.['table-joker'],target);
 assert.equal(moved.melds[0].cards[position].id,'table-joker');
 assert.equal(moved.melds[0].cards.length,6);
 assert.equal(moved.players[0].hand.some(c=>c.id==='natural-four'),false);
 assert.equal(score(moved)[0].canastas,0);
}
const wrongSuit=structuredClone(replace);wrongSuit.players[0].hand[0].s='♥';
assert.equal(meldOptions([wrongSuit.players[0].hand[0]],wrongSuit.melds[0]).length,0);
assert.throws(()=>action(wrongSuit,0,'meld',{ids:['natural-four'],meldId:'gap',wildRank:2}),/Forme uma sequência/);
const littleWild=structuredClone(replace);littleWild.melds[0].cards[1]={id:'table-joker',r:2,s:'♦'};
assert.equal(action(littleWild,0,'meld',{ids:['natural-four'],meldId:'gap',wildRank:8}).melds[0].wilds?.['table-joker'],8);
let partner=newGame('partner-drop',['A','B','C','D']);for(let i=1;i<4;i++)partner=action(partner,i,'join');
partner.turn=2;partner.drawn=true;partner.players[2].hand=[{id:'partner-six',r:6,s:'♣'},{id:'spare',r:9,s:'♦'}];
partner.melds=[{id:'team-zero',team:0,cards:cards([3,4,5],'♣')},{id:'team-one',team:1,cards:cards([3,4,5],'♣')}];
assert.throws(()=>action(partner,2,'meld',{ids:['partner-six'],meldId:'team-one'}),/Escolha um jogo da sua equipe/);
partner=action(partner,2,'meld',{ids:['partner-six'],meldId:'team-zero'});
assert.equal(partner.melds[0].cards.length,4);
let blocked=newGame('blocked',['A','B']);blocked=action(blocked,1,'join');blocked.taken[0]=true;blocked.drawn=true;
blocked.players[0].hand=[...cards([6]),...cards([13],'♠')];blocked.melds=[{id:'short',team:0,cards:cards([3,4,5])}];
assert.throws(()=>action(blocked,0,'meld',{ids:['♥-6-0'],meldId:'short'}),/deixaria uma carta na mão sem canastra/);
assert.deepEqual(blocked.players[0].hand.map(c=>c.id),['♥-6-0','♠-13-0']);assert.equal(blocked.melds[0].cards.length,3);
blocked=action(blocked,0,'discard',{ids:['♠-13-0']});assert.equal(blocked.turn,1);assert.equal(blocked.players[0].hand.length,1);
let finishable=newGame('finishable',['A','B']);finishable=action(finishable,1,'join');finishable.taken[0]=true;finishable.drawn=true;
finishable.players[0].hand=[...cards([9],'♠'),...cards([9])];
finishable.melds=[{id:'six',team:0,cards:cards([3,4,5,6,7,8])},{id:'other',team:0,cards:cards([10,11,12],'♠')}];
finishable=action(finishable,0,'meld',{ids:['♠-9-0'],meldId:'other'});assert.equal(finishable.players[0].hand.length,1);
finishable=action(finishable,0,'meld',{ids:['♥-9-0'],meldId:'six'});assert.equal(finishable.winner,0);
let movableFinish=newGame('movable-finish',['A','B']);movableFinish=action(movableFinish,1,'join');movableFinish.taken[0]=true;movableFinish.drawn=true;
movableFinish.players[0].hand=[{id:'other-card',r:9,s:'♥'},{id:'last-four',r:4,s:'♠'}];
movableFinish.melds=[{id:'almost',team:0,cards:[{id:'three',r:3,s:'♠'},{id:'wild',r:0,s:'★'},...cards([5,6,7,8],'♠')],wilds:{wild:4}},{id:'other',team:0,cards:cards([10,11,12],'♥')}];
movableFinish=action(movableFinish,0,'meld',{ids:['other-card'],meldId:'other'});
assert.equal(movableFinish.players[0].hand.length,1);
movableFinish=action(movableFinish,0,'meld',{ids:['last-four'],meldId:'almost',wildRank:2});
assert.equal(movableFinish.winner,0);
let wildFinish=newGame('wild-finish',['A','B']);wildFinish=action(wildFinish,1,'join');wildFinish.taken[0]=true;wildFinish.drawn=true;
wildFinish.players[0].hand=[...cards([9],'♠'),{id:'last-joker',r:0,s:'★'}];
wildFinish.melds=[{id:'gap',team:0,cards:cards([3,4,5,7,8,9])},{id:'other',team:0,cards:cards([10,11,12],'♠')}];
wildFinish=action(wildFinish,0,'meld',{ids:['♠-9-0'],meldId:'other'});
wildFinish=action(wildFinish,0,'meld',{ids:['last-joker'],meldId:'gap',wildRank:6});assert.equal(wildFinish.winner,0);
console.log('PASS: 2/4 players, 108 unique cards, concealed hands, turn checks, wildcard placement, morto, finish, deadlock prevention, scoring, unlimited rounds.');
